services:
  - type: web
    plan: free
    name: SaveResbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app & python3 app.py
    repo: https://github.com/nonamebesty/SaveResbot.git
    branch: main
    autoDeploy: false
    envVars:
      - key: TOKEN1
        sync: false
      - key: ID
        sync: false
      - key: HASH
        sync: false
      - key: STRING
        sync: false
